FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

Run pip install --upgrade pip

COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt 

# COPY convert_model_onnx.py /app/convert_model.py
# RUN python /app/convert_model.py

# ENTRYPOINT ["/app/convert_model.py"]